In [2]:
from sklearn.datasets import load_iris, fetch_20newsgroups, fetch_california_housing
from sklearn.model_selection import train_test_split, GridSearchCV
from pprint import pprint
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score

# 使用数据集
小规模只能用load下载到内存, 大规模可以fetch保存到硬盘

In [3]:
#鸢尾花数据集，查看特征，目标，样本量

li = load_iris()
# li.data是特征值
print(type(li.data))
print('-' * 50)
print(li.data.shape) 
# 150个样本，4个特征,一般看shape
li.data[:5]
# 显示前五个样本

<class 'numpy.ndarray'>
--------------------------------------------------
(150, 4)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
print(li.data.shape)
li.target.shape
# 150个样本，4个特征, 每个样本有一个目标值

(150, 4)

(150,)

In [5]:
print(li.target)
# 目标值/标签值
print('-' * 50)
print(li.DESCR)
# 数据集描述
print('-' * 50)
print(li.feature_names)  
# 特征值名字
print('-' * 50)
print(li.target_names) 
# 目标值名字

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
--------------------------------------------------
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

--------------------------------------------------
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
--------------------------------------------------
['setosa' 'versicolor' 'virginica']

In [6]:
# 使用20类新闻数据集
# subset代表下载的数据集类型，默认是train，只有训练集
news = fetch_20newsgroups(subset='all', data_home='data')
# print(news.feature_names)  
# 没有特征, 只有文本数据
print(news.DESCR)
print('第一个样本')
print(news.data[0])

.. _20newsgroups_dataset:

The 20 newsgroups text dataset
------------------------------

The 20 newsgroups dataset comprises around 18000 newsgroups posts on
20 topics split in two subsets: one for training (or development)
and the other one for testing (or for performance evaluation). The split
between the train and test set is based upon a messages posted before
and after a specific date.

This module contains two loaders. The first one,
:func:`sklearn.datasets.fetch_20newsgroups`,
returns a list of the raw texts that can be fed to text feature
extractors such as :class:`~sklearn.feature_extraction.text.CountVectorizer`
with custom parameters so as to extract feature vectors.
The second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,
returns ready-to-use features, i.e., it is not necessary to use a feature
extractor.

**Data Set Characteristics:**

=================   ==========
Classes                     20
Samples total            18846
Dimensionality               1
Features                  text
=================   ==========

.. dropdown:: Usage

  The :func:`sklearn.datasets.fetch_20newsgroups` function is a data
  fetching / caching functions that downloads the data archive from
  the original `20 newsgroups website <http://people.csail.mit.edu/jrennie/20Newsgroups/>`__,
  extracts the archive contents
  in the ``~/scikit_learn_data/20news_home`` folder and calls the
  :func:`sklearn.datasets.load_files` on either the training or
  testing set folder, or both of them::

    >>> from sklearn.datasets import fetch_20newsgroups
    >>> newsgroups_train = fetch_20newsgroups(subset='train')

    >>> from pprint import pprint
    >>> pprint(list(newsgroups_train.target_names))
    ['alt.atheism',
     'comp.graphics',
     'comp.os.ms-windows.misc',
     'comp.sys.ibm.pc.hardware',
     'comp.sys.mac.hardware',
     'comp.windows.x',
     'misc.forsale',
     'rec.autos',
     'rec.motorcycles',
     'rec.sport.baseball',
     'rec.sport.hockey',
     'sci.crypt',
     'sci.electronics',
     'sci.med',
     'sci.space',
     'soc.religion.christian',
     'talk.politics.guns',
     'talk.politics.mideast',
     'talk.politics.misc',
     'talk.religion.misc']

  The real data lies in the ``filenames`` and ``target`` attributes. The target
  attribute is the integer index of the category::

    >>> newsgroups_train.filenames.shape
    (11314,)
    >>> newsgroups_train.target.shape
    (11314,)
    >>> newsgroups_train.target[:10]
    array([ 7,  4,  4,  1, 14, 16, 13,  3,  2,  4])

  It is possible to load only a sub-selection of the categories by passing the
  list of the categories to load to the
  :func:`sklearn.datasets.fetch_20newsgroups` function::

    >>> cats = ['alt.atheism', 'sci.space']
    >>> newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)

    >>> list(newsgroups_train.target_names)
    ['alt.atheism', 'sci.space']
    >>> newsgroups_train.filenames.shape
    (1073,)
    >>> newsgroups_train.target.shape
    (1073,)
    >>> newsgroups_train.target[:10]
    array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0])

.. dropdown:: Converting text to vectors

  In order to feed predictive or clustering models with the text data,
  one first need to turn the text into vectors of numerical values suitable
  for statistical analysis. This can be achieved with the utilities of the
  ``sklearn.feature_extraction.text`` as demonstrated in the following
  example that extract `TF-IDF <https://en.wikipedia.org/wiki/Tf-idf>`__ vectors
  of unigram tokens from a subset of 20news::

    >>> from sklearn.feature_extraction.text import TfidfVectorizer
    >>> categories = ['alt.atheism', 'talk.religion.misc',
    ...               'comp.graphics', 'sci.space']
    >>> newsgroups_train = fetch_20newsgroups(subset='train',
    ...                                       categories=categories)
    >>> vectorizer = TfidfVectorizer()
    >>> vectors = vectorizer.fit_transform(newsgroups_train.data)
    >>> vectors.shape
    (2034, 34118)

  The extracted TF-IDF vectors are very sparse, with an average of 159 non-zero
  components by sample in a more than 30000-dimensional space
  (less than .5% non-zero features)::

    >>> vectors.nnz / float(vectors.shape[0])
    159.01327...

  :func:`sklearn.datasets.fetch_20newsgroups_vectorized` is a function which
  returns ready-to-use token counts features instead of file names.

.. dropdown:: Filtering text for more realistic training

  It is easy for a classifier to overfit on particular things that appear in the
  20 Newsgroups data, such as newsgroup headers. Many classifiers achieve very
  high F-scores, but their results would not generalize to other documents that
  aren't from this window of time.

  For example, let's look at the results of a multinomial Naive Bayes classifier,
  which is fast to train and achieves a decent F-score::

    >>> from sklearn.naive_bayes import MultinomialNB
    >>> from sklearn import metrics
    >>> newsgroups_test = fetch_20newsgroups(subset='test',
    ...                                      categories=categories)
    >>> vectors_test = vectorizer.transform(newsgroups_test.data)
    >>> clf = MultinomialNB(alpha=.01)
    >>> clf.fit(vectors, newsgroups_train.target)
    MultinomialNB(alpha=0.01, class_prior=None, fit_prior=True)

    >>> pred = clf.predict(vectors_test)
    >>> metrics.f1_score(newsgroups_test.target, pred, average='macro')
    0.88213...

  (The example :ref:`sphx_glr_auto_examples_text_plot_document_classification_20newsgroups.py` shuffles
  the training and test data, instead of segmenting by time, and in that case
  multinomial Naive Bayes gets a much higher F-score of 0.88. Are you suspicious
  yet of what's going on inside this classifier?)

  Let's take a look at what the most informative features are:

    >>> import numpy as np
    >>> def show_top10(classifier, vectorizer, categories):
    ...     feature_names = vectorizer.get_feature_names_out()
    ...     for i, category in enumerate(categories):
    ...         top10 = np.argsort(classifier.coef_[i])[-10:]
    ...         print("%s: %s" % (category, " ".join(feature_names[top10])))
    ...
    >>> show_top10(clf, vectorizer, newsgroups_train.target_names)
    alt.atheism: edu it and in you that is of to the
    comp.graphics: edu in graphics it is for and of to the
    sci.space: edu it that is in and space to of the
    talk.religion.misc: not it you in is that and to of the


  You can now see many things that these features have overfit to:

  - Almost every group is distinguished by whether headers such as
    ``NNTP-Posting-Host:`` and ``Distribution:`` appear more or less often.
  - Another significant feature involves whether the sender is affiliated with
    a university, as indicated either by their headers or their signature.
  - The word "article" is a significant feature, based on how often people quote
    previous posts like this: "In article [article ID], [name] <[e-mail address]>
    wrote:"
  - Other features match the names and e-mail addresses of particular people who
    were posting at the time.

  With such an abundance of clues that distinguish newsgroups, the classifiers
  barely have to identify topics from text at all, and they all perform at the
  same high level.

  For this reason, the functions that load 20 Newsgroups data provide a
  parameter called **remove**, telling it what kinds of information to strip out
  of each file. **remove** should be a tuple containing any subset of
  ``('headers', 'footers', 'quotes')``, telling it to remove headers, signature
  blocks, and quotation blocks respectively.

    >>> newsgroups_test = fetch_20newsgroups(subset='test',
    ...                                      remove=('headers', 'footers', 'quotes'),
    ...                                      categories=categories)
    >>> vectors_test = vectorizer.transform(newsgroups_test.data)
    >>> pred = clf.predict(vectors_test)
    >>> metrics.f1_score(pred, newsgroups_test.target, average='macro')
    0.77310...

  This classifier lost over a lot of its F-score, just because we removed
  metadata that has little to do with topic classification.
  It loses even more if we also strip this metadata from the training data:

    >>> newsgroups_train = fetch_20newsgroups(subset='train',
    ...                                       remove=('headers', 'footers', 'quotes'),
    ...                                       categories=categories)
    >>> vectors = vectorizer.fit_transform(newsgroups_train.data)
    >>> clf = MultinomialNB(alpha=.01)
    >>> clf.fit(vectors, newsgroups_train.target)
    MultinomialNB(alpha=0.01, class_prior=None, fit_prior=True)

    >>> vectors_test = vectorizer.transform(newsgroups_test.data)
    >>> pred = clf.predict(vectors_test)
    >>> metrics.f1_score(newsgroups_test.target, pred, average='macro')
    0.76995...

  Some other classifiers cope better with this harder version of the task. Try the
  :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_text_feature_extraction.py`
  example with and without the `remove` option to compare the results.

.. rubric:: Data Considerations

The Cleveland Indians is a major league baseball team based in Cleveland,
Ohio, USA. In December 2020, it was reported that "After several months of
discussion sparked by the death of George Floyd and a national reckoning over
race and colonialism, the Cleveland Indians have decided to change their
name." Team owner Paul Dolan "did make it clear that the team will not make
its informal nickname -- the Tribe -- its new team name." "It's not going to
be a half-step away from the Indians," Dolan said."We will not have a Native
American-themed name."

https://www.mlb.com/news/cleveland-indians-team-name-change

.. rubric:: Recommendation

- When evaluating text classifiers on the 20 Newsgroups data, you
  should strip newsgroup-related metadata. In scikit-learn, you can do this
  by setting ``remove=('headers', 'footers', 'quotes')``. The F-score will be
  lower because it is more realistic.
- This text dataset contains data which may be inappropriate for certain NLP
  applications. An example is listed in the "Data Considerations" section
  above. The challenge with using current text datasets in NLP for tasks such
  as sentence completion, clustering, and other applications is that text
  that is culturally biased and inflammatory will propagate biases. This
  should be taken into consideration when using the dataset, reviewing the
  output, and the bias should be documented.

.. rubric:: Examples

* :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_text_feature_extraction.py`
* :ref:`sphx_glr_auto_examples_text_plot_document_classification_20newsgroups.py`
* :ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`
* :ref:`sphx_glr_auto_examples_text_plot_document_clustering.py`

第一个样本
From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!

In [7]:
print(type(news.data))
# 特征是一个列表

<class 'list'>

In [8]:
print(news.target[0:30])
pprint(list(news.target_names))
# pretty print漂亮打印
len(news.target_names)
# 共20种target

[10  3 17  3  4 12  4 10 10 19 19 11 19 13  0 17 12 12 11  8  7  5  1  8
 10 14 16  1  6  0]
['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

20

In [9]:
x_train, x_test, y_train, y_test = train_test_split(li.data, li.target, test_size=0.25, random_state=1)
# 划分训练集与测试集的函数, 返回值顺序是:
# 训练集特征值, 测试集特征值, 训练集目标值, 测试集目标值
# 测试集占比25%
# random_state指定随机种子，保证每次运行结果一致

print("训练集特征值和目标值：", x_train.shape, y_train.shape)
print("训练集特征值的shape", x_train.shape)
print('-'*50)
print("测试集特征值和目标值：", x_test.shape, y_test.shape)
print("测试集特征值的shape", x_test.shape)

训练集特征值和目标值： (112, 4) (112,)
训练集特征值的shape (112, 4)
--------------------------------------------------
测试集特征值和目标值： (38, 4) (38,)
测试集特征值的shape (38, 4)

In [10]:
print(len(news.data))
print(len(news.target))
print('-' * 50)
print(min(news.target), max(news.target))

18846
18846
--------------------------------------------------
0 19

In [11]:
# 使用加利福尼亚房价数据集
house=fetch_california_housing(data_home='data')
print(house.feature_names)
# 特征名字
print(house.data[0])  
# 第一个样本特征值
print(house.data.shape)
print('-' * 50)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
[   8.3252       41.            6.98412698    1.02380952  322.
    2.55555556   37.88       -122.23      ]
(20640, 8)
--------------------------------------------------

In [12]:
print(house.target[0])
print(house.target.shape)
print('-' * 50)
print(house.DESCR)
print('-' * 50)

4.526
(20640,)
--------------------------------------------------
.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

--------------------------------------------------

# 分类估计器

做数据预处理的是转换器, 做分类/回归的是估计器

使用KNN(k-近邻)预测用户签到位置

优点:  
1.训练时间复杂度为0  
2.既可以做分类也可以做回归, 算法简单,理论成熟  
3.可用于非线性分类  
缺点:  
预测的时间复杂度和空间复杂度高, 对稀有类别的预测准确度低

In [13]:
data = pd.read_csv("./data/FBlocation/train.csv")

print(data.head(10))
print(data.shape)
data.info()

   row_id       x       y  accuracy    time    place_id
0       0  0.7941  9.0809        54  470702  8523065625
1       1  5.9567  4.7968        13  186555  1757726713
2       2  8.3078  7.0407        74  322648  1137537235
3       3  7.3665  2.5165        65  704587  6567393236
4       4  4.0961  1.1307        31  472130  7440663949
5       5  3.8099  1.9586        75  178065  6289802927
6       6  6.3336  4.3720        13  666829  9931249544
7       7  5.7409  6.7697        85  369002  5662813655
8       8  4.3114  6.9410         3  166384  8471780938
9       9  6.3414  0.0758        65  400060  1253803156
(29118021, 6)
<class 'pandas.DataFrame'>
RangeIndex: 29118021 entries, 0 to 29118020
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   row_id    int64
 1   x         float64
 2   y         float64
 3   accuracy  int64
 4   time      int64
 5   place_id  int64
dtypes: float64(2), int64(4)
memory usage: 1.3 GB

In [14]:
# 只处理部分数据
data = data.query("x > 1.0 &  x < 1.25 & y > 2.5 & y < 2.75")
# query用字符串写类似SQL的条件表达式
# 等价于
#  data = data[
#     (data["x"] > 1.0) & (data["x"] < 1.25) &
#     (data["y"] > 2.5) & (data["y"] < 2.75)
# ]
# 使用 & 而不是and, 因为是逐元素运算
print(data.shape)
print(data.describe())
data
# 筛选了之后行号不是连续的了

(17710, 6)
             row_id             x             y      accuracy           time  \
count  1.771000e+04  17710.000000  17710.000000  17710.000000   17710.000000
mean   1.450569e+07      1.122538      2.632309     82.482101  397551.263128
std    8.353805e+06      0.077086      0.070144    113.613227  234601.097883
min    6.000000e+02      1.000100      2.500100      1.000000     119.000000
25%    7.327816e+06      1.049200      2.573800     25.000000  174069.750000
50%    1.443071e+07      1.123300      2.642300     62.000000  403387.500000
75%    2.163463e+07      1.190500      2.687800     75.000000  602111.750000
max    2.911215e+07      1.249900      2.749900   1004.000000  786218.000000

           place_id
count  1.771000e+04
mean   5.129895e+09
std    2.357399e+09
min    1.012024e+09
25%    3.312464e+09
50%    5.261906e+09
75%    6.766325e+09
max    9.980711e+09

            row_id       x       y  accuracy    time    place_id
600            600  1.2214  2.7023        17   65380  6683426742
957            957  1.1832  2.6891        58  785470  6683426742
4345          4345  1.1935  2.6550        11  400082  6889790653
4735          4735  1.1452  2.6074        49  514983  6822359752
5580          5580  1.0089  2.7287        19  732410  1527921905
...            ...     ...     ...       ...     ...         ...
29100203  29100203  1.0129  2.6775        12   38036  3312463746
29108443  29108443  1.1474  2.6840        36  602524  3533177779
29109993  29109993  1.0240  2.7238        62  658994  6424972551
29111539  29111539  1.2032  2.6796        87  262421  3533177779
29112154  29112154  1.1070  2.5419       178  687667  4932578245

[17710 rows x 6 columns]

In [15]:
time_value = pd.to_datetime(data['time'], unit='s')
# 将时间戳转换为时间
print(time_value.head(10))

600    1970-01-01 18:09:40
957    1970-01-10 02:11:10
4345   1970-01-05 15:08:02
4735   1970-01-06 23:03:03
5580   1970-01-09 11:26:50
6090   1970-01-02 16:25:07
6234   1970-01-04 15:52:57
6350   1970-01-01 10:13:36
7468   1970-01-09 15:26:06
8478   1970-01-08 23:52:02
Name: time, dtype: datetime64[s]

In [16]:
# 把日期格式转换成 索引格式
time_value = pd.DatetimeIndex(time_value)
print(time_value[0:10])

DatetimeIndex(['1970-01-01 18:09:40', '1970-01-10 02:11:10',
               '1970-01-05 15:08:02', '1970-01-06 23:03:03',
               '1970-01-09 11:26:50', '1970-01-02 16:25:07',
               '1970-01-04 15:52:57', '1970-01-01 10:13:36',
               '1970-01-09 15:26:06', '1970-01-08 23:52:02'],
              dtype='datetime64[s]', name='time', freq=None)

In [17]:
# 时间本身作为特征不合适, 我们更加关心签到时间在一个月内是几号, 在一个星期内是星期几, 在一天内是几点
# 虽然脱敏过, 但是分布不会改变
print(type(data))

data.insert(data.shape[1], 'day', time_value.day) 
data.insert(data.shape[1], 'hour', time_value.hour)
data.insert(data.shape[1], 'weekday', time_value.weekday) 
# insert相当于直接赋值, data.shape[1]表示插入到最后
# data['day'] = time_value.day
# data['hour'] = time_value.hour
# data['weekday'] = time_value.weekday
data = data.drop(['time'], axis=1)
# 删除时间戳
print('-' * 50)
data.head()

<class 'pandas.DataFrame'>
--------------------------------------------------

      row_id       x       y  accuracy    place_id  day  hour  weekday
600      600  1.2214  2.7023        17  6683426742    1    18        3
957      957  1.1832  2.6891        58  6683426742   10     2        5
4345    4345  1.1935  2.6550        11  6889790653    5    15        0
4735    4735  1.1452  2.6074        49  6822359752    6    23        1
5580    5580  1.0089  2.7287        19  1527921905    9    11        4

In [18]:
data.describe()

,row_id,x,y,accuracy,place_id,day,hour,weekday
count,1.771000e+04,17710.000000,17710.000000,17710.000000,1.771000e+04,17710.000000,17710.000000,17710.000000
mean,1.450569e+07,1.122538,2.632309,82.482101,5.129895e+09,5.101863,11.485545,3.092377
std,8.353805e+06,0.077086,0.070144,113.613227,2.357399e+09,2.709287,6.932195,1.680218
min,6.000000e+02,1.000100,2.500100,1.000000,1.012024e+09,1.000000,0.000000,0.000000
25%,7.327816e+06,1.049200,2.573800,25.000000,3.312464e+09,3.000000,6.000000,2.000000
50%,1.443071e+07,1.123300,2.642300,62.000000,5.261906e+09,5.000000,12.000000,3.000000
75%,2.163463e+07,1.190500,2.687800,75.000000,6.766325e+09,7.000000,17.000000,4.000000
max,2.911215e+07,1.249900,2.749900,1004.000000,9.980711e+09,10.000000,23.000000,6.000000

In [19]:
place_count = data.groupby('place_id').count()
print(place_count)
# 有805个不同的签到位置, 有些地点打卡数非常多

            row_id     x     y  accuracy   day  hour  weekday
place_id
1012023972       1     1     1         1     1     1        1
1057182134       1     1     1         1     1     1        1
1059958036       3     3     3         3     3     3        3
1085266789       1     1     1         1     1     1        1
1097200869    1044  1044  1044      1044  1044  1044     1044
...            ...   ...   ...       ...   ...   ...      ...
9904182060       1     1     1         1     1     1        1
9915093501       1     1     1         1     1     1        1
9946198589       1     1     1         1     1     1        1
9950190890       1     1     1         1     1     1        1
9980711012       5     5     5         5     5     5        5

[805 rows x 7 columns]

In [20]:
place_count['x'].describe()
# 有50%的签到位置签到数小于两次

count     805.000000
mean       22.000000
std        88.955632
min         1.000000
25%         1.000000
50%         2.000000
75%         5.000000
max      1044.000000
Name: x, dtype: float64

In [21]:
tf = place_count[place_count.x > 5].reset_index()
# 筛选出签到数大于5的地点
tf 
# 只剩下188个签到地点

       place_id  row_id     x     y  accuracy   day  hour  weekday
0    1097200869    1044  1044  1044      1044  1044  1044     1044
1    1228935308     120   120   120       120   120   120      120
2    1267801529      58    58    58        58    58    58       58
3    1278040507      15    15    15        15    15    15       15
4    1285051622      21    21    21        21    21    21       21
..          ...     ...   ...   ...       ...   ...   ...      ...
183  9710472407      48    48    48        48    48    48       48
184  9713454201     123   123   123       123   123   123      123
185  9753855529      21    21    21        21    21    21       21
186  9806043737       6     6     6         6     6     6        6
187  9809476069      23    23    23        23    23    23       23

[188 rows x 8 columns]

In [22]:
data = data[data['place_id'].isin(tf.place_id)]
data
# 筛选过后仍然剩下16694个样本, 即188个签到地点包含了大部分样本

            row_id       x       y  accuracy    place_id  day  hour  weekday
600            600  1.2214  2.7023        17  6683426742    1    18        3
957            957  1.1832  2.6891        58  6683426742   10     2        5
4345          4345  1.1935  2.6550        11  6889790653    5    15        0
5580          5580  1.0089  2.7287        19  1527921905    9    11        4
6090          6090  1.1140  2.6262        11  4000153867    2    16        4
...            ...     ...     ...       ...         ...  ...   ...      ...
29100203  29100203  1.0129  2.6775        12  3312463746    1    10        3
29108443  29108443  1.1474  2.6840        36  3533177779    7    23        2
29109993  29109993  1.0240  2.7238        62  6424972551    8    15        3
29111539  29111539  1.2032  2.6796        87  3533177779    4     0        6
29112154  29112154  1.1070  2.5419       178  4932578245    8    23        3

[16694 rows x 8 columns]

In [23]:
# 取出目标值
y = data['place_id']
# 一般设目标值为y
x = data.drop(['place_id'], axis=1)
x = x.drop(['row_id'], axis=1)
# 删除无用的特征值(row_id)和目标值
print(x.shape)
print(x.columns)

(16694, 6)
Index(['x', 'y', 'accuracy', 'day', 'hour', 'weekday'], dtype='str')

预处理完成

In [24]:
# 在给出的完整数据中, 分割训练集和测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

std = StandardScaler()
x_train = std.fit_transform(x_train)
# 对训练集特征值进行标准化

print(std.mean_)
print(std.var_)
x_test = std.transform(x_test)  
print(id(x_test))
# transform 不再进行均值和方差的计算，是在原有的基础上去标准化
# 返回的是副本
print('-' * 50)
print(id(x_test))
print(std.mean_)
print(std.var_)
# 使用的仍是fit得到的参数

[ 1.12177381  2.63342181 81.63306709  5.07763578 11.52995208  3.10015974]
[5.96369981e-03 4.85778983e-03 1.19817523e+04 7.40707173e+00
 4.83751412e+01 2.77926515e+00]
2161317400944
--------------------------------------------------
2161317400944
[ 1.12177381  2.63342181 81.63306709  5.07763578 11.52995208  3.10015974]
[5.96369981e-03 4.85778983e-03 1.19817523e+04 7.40707173e+00
 4.83751412e+01 2.77926515e+00]

In [25]:
x_train.shape

(12520, 6)

In [26]:
knn = KNeighborsClassifier(n_neighbors=3)
# KNN分类器, 参数n_neighbors是超参数, 纳入多少个邻居
knn.fit(x_train, y_train)
# knn的fit是不训练的，只是把训练集的特征值和目标值放入到内存中
y_predict = knn.predict(x_test)
# 计算发生在预测阶段, 每个点都找最近三个点投票
# 得出预测结果
print("预测的签到位置：", y_predict[0:10])
print("预测的准确率:", knn.score(x_test, y_test))
# 得出准确率, score指用x_test预测出的y_predict去和y_test比较
# 等价于
# from sklearn.metrics import accuracy_score
# accuracy_score(y_test, knn.predict(x_test))

预测的签到位置： [4932578245 3312463746 1097200869 3312463746 2355236719 1097200869
 3202755803 1097200869 9598377925 3952821602]
预测的准确率: 0.464302827024437

In [27]:
print(y_predict[0:10])
print(y_test.to_numpy()[0:10])

[4932578245 3312463746 1097200869 3312463746 2355236719 1097200869
 3202755803 1097200869 9598377925 3952821602]
[4932578245 3312463746 5095999304 3312463746 1812226671 1097200869
 6237569496 1097200869 5270522918 5270522918]

# 网格搜索-调整超参数

In [28]:
param = {"n_neighbors": [3, 5, 10, 12, 15],'weights':['uniform', 'distance']}
# weights参数是距离权重，uniform是距离权重相同，distance是距离越近权重越大
gc = GridSearchCV(knn, param_grid=param, cv=3)
# 将多个参数组成5*2个组合, 进行网格搜索，cv=3是3折交叉验证，用其中2折训练，1折验证
gc.fit(x_train, y_train)
# 给出的训练集, 又被分为训练集, 验证集

print("在测试集上最好的准确率：", gc.score(x_test, y_test))
# 在测试集上最好的准确率
print("在交叉验证当中最好的准确率：", gc.best_score_)
# 三折交叉验证的最好的准确率
print("选择最好的模型是：", gc.best_estimator_) 
print("每个超参数每次交叉验证的结果：")
gc.cv_results_
# 训练集分成三折, 以每折为验证集的情况下, 有10个参数组合, 共30个结果

在测试集上最好的准确率： 0.5031145184475323
在交叉验证当中最好的准确率： 0.4900962228835266
选择最好的模型是： KNeighborsClassifier(n_neighbors=10, weights='distance')
每个超参数每次交叉验证的结果：

{'mean_fit_time': array([0.00734043, 0.00762526, 0.0069952 , 0.00707547, 0.00867836,
        0.00732501, 0.00752457, 0.00766261, 0.00752703, 0.00700784]),
 'std_fit_time': array([2.55973260e-04, 6.72251455e-04, 4.09097520e-04, 4.24226914e-04,
        1.74589262e-03, 2.84978483e-04, 3.56972217e-04, 6.33316980e-04,
        2.76293657e-05, 7.20849180e-04]),
 'mean_score_time': array([0.0386982 , 0.05258369, 0.05092017, 0.06203667, 0.06602637,
        0.10688019, 0.07729808, 0.09077883, 0.07877787, 0.10103424]),
 'std_score_time': array([0.00013614, 0.0013209 , 0.00257788, 0.0006013 , 0.00168821,
        0.0121114 , 0.00486744, 0.00089077, 0.000235  , 0.00041365]),
 'param_n_neighbors': masked_array(data=[3, 3, 5, 5, 10, 10, 12, 12, 15, 15],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_neighbors': 3, 'weights': 'uniform'},
  {'n_neighbors': 3, 'weights': 'distance'},
  {'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 10, 'weights': 'uniform'},
  {'n_neighbors': 10, 'weights': 'distance'},
  {'n_neighbors': 12, 'weights': 'uniform'},
  {'n_neighbors': 12, 'weights': 'distance'},
  {'n_neighbors': 15, 'weights': 'uniform'},
  {'n_neighbors': 15, 'weights': 'distance'}],
 'split0_test_score': array([0.45543843, 0.46478198, 0.47053186, 0.47843795, 0.46142789,
        0.48538572, 0.45831337, 0.48466699, 0.45591759, 0.47987542]),
 'split1_test_score': array([0.44859813, 0.462497  , 0.46776899, 0.48166786, 0.46728972,
        0.4886173 , 0.46273664, 0.48933621, 0.45962138, 0.48502277]),
 'split2_test_score': array([0.45219267, 0.46657081, 0.46944644, 0.48813803, 0.47687515,
        0.49628565, 0.47735442, 0.4953271 , 0.4684879 , 0.49436856]),
 'mean_test_score': array([0.45207641, 0.4646166 , 0.4692491 , 0.48274795, 0.46853092,
        0.49009622, 0.46613481, 0.48977677, 0.46134229, 0.48642225]),
 'std_test_score': array([0.00279375, 0.00166723, 0.00113654, 0.00403302, 0.0063671 ,
        0.0045711 , 0.00813638, 0.00436311, 0.00527411, 0.00599898]),
 'rank_test_score': array([10,  8,  5,  4,  6,  1,  7,  2,  9,  3], dtype=int32)}

# 朴素贝叶斯文本分类

优点:
1.来源于古典数学理论,分类效率稳定  
2.对缺失数据不太敏感, 常用于文本分类(指的是缺少段落而不是NaN)  
3.分类速度快,准确率高  
缺点: 先验概率无法准确得知

In [29]:
news = fetch_20newsgroups(subset='all', data_home='data')

print(len(news.data))  
print('-'*50)
print(news.data[0]) 
print('-'*50)
print(news.target[0:5]) 
print(np.unique(news.target)) 
# 标签一共有哪些类别
print(news.target_names) 
# 标签的名字

18846
--------------------------------------------------
From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!


--------------------------------------------------
[10  3 17  3  4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']

In [30]:
x_train, x_test, y_train, y_test = train_test_split(news.data, news.target, test_size=0.25, random_state=1)
# 分割训练集和测试集
tf = TfidfVectorizer()
print(len(x_train))
x_train = tf.fit_transform(x_train)
# 得到训练集每个词的TF-IDF值, 值越大表示越重要
print(len(tf.get_feature_names_out()))
# 一共出现了多少个特征(单词)

14134
153196

In [31]:
x_train.shape

(14134, 153196)

In [32]:
print(tf.get_feature_names_out()[100000])

murky

In [33]:
import time
mlt = MultinomialNB(alpha=1.0)
# 进行朴素贝叶斯算法的预测, 公式是：P(y|x) = P(y) * P(x|y)/P(x)
# y指一个标签, x指一组特征, 给出一组特征, 是某个标签的概率, 等于该标签的先验概率, 乘以该标签下特征出现的概率, 除以特征出现的概率
# 因为特征是给定的, 所以忽略P(x)
# 训练是计算每种标签-特征组合的概率, 得到出现每个特征时, 是每个类别的概率
# alpha是拉普拉斯平滑系数，计算每个特征的 P(x|y)时, 分子加上alpha，分母加alpha*特征词数目
# 防止某类中没出现过某个特征, 遇到该特征时算出概率0
# 以防预测集中某篇文章, 无论多么符合某一类, 但因训练集中该类不包含该文章中的某个词, 完全无法匹配到该类
# print(x_train.toarray()[0])
# 训练
start=time.time()
mlt.fit(x_train, y_train) 
# 训练模型, 传入的是一个稀疏存储的矩阵, 自动转换成了array
end=time.time()
end-start #统计训练时间

0.13495707511901855

In [34]:
x_transform_test = tf.transform(x_test)  
# 使用训练集的特征处理测试集, 遇到新词会被丢弃
print(len(tf.get_feature_names_out()))

153196

In [35]:
x_transform_test.shape

(4712, 153196)

In [36]:
start=time.time()
y_predict = mlt.predict(x_transform_test)
print("前十篇文章预测的类别为：", y_predict[0:10])
print("前十篇文章真实的类别为：", y_test[0:10])
print("准确率为：", mlt.score(x_transform_test, y_test))
end=time.time()
end-start 
#预测时间

前十篇文章预测的类别为： [16 19 18  1  9 15  1  2 16 13]
前十篇文章真实的类别为： [16 19 18  1  9 19  1  3 16 13]
准确率为： 0.8518675721561969

0.05776643753051758

In [37]:
print(classification_report(y_test, y_predict,
      target_names=news.target_names))
# 计算对于每个标签的精确率, 召回率, F1分数, support指事实上是每个标签的样本数
# 精确率是预测为真的结果中，实际为真的概率, TP/(TP+FP)
# 召回率是实际为真的结果中，预测为真的概率, TP/(TP+FN)
# F1分数是2TP/(2TP+FP+FN)

                          precision    recall  f1-score   support

             alt.atheism       0.91      0.77      0.83       199
           comp.graphics       0.83      0.79      0.81       242
 comp.os.ms-windows.misc       0.89      0.83      0.86       263
comp.sys.ibm.pc.hardware       0.80      0.83      0.81       262
   comp.sys.mac.hardware       0.90      0.88      0.89       234
          comp.windows.x       0.92      0.85      0.88       230
            misc.forsale       0.96      0.67      0.79       257
               rec.autos       0.90      0.87      0.88       265
         rec.motorcycles       0.90      0.95      0.92       251
      rec.sport.baseball       0.89      0.96      0.93       226
        rec.sport.hockey       0.95      0.98      0.96       262
               sci.crypt       0.76      0.97      0.85       257
         sci.electronics       0.84      0.80      0.82       229
                 sci.med       0.97      0.86      0.91       249
               sci.space       0.92      0.96      0.94       256
  soc.religion.christian       0.55      0.98      0.70       243
      talk.politics.guns       0.76      0.96      0.85       234
   talk.politics.mideast       0.93      0.99      0.96       224
      talk.politics.misc       0.98      0.56      0.72       197
      talk.religion.misc       0.97      0.26      0.41       132

                accuracy                           0.85      4712
               macro avg       0.88      0.84      0.84      4712
            weighted avg       0.87      0.85      0.85      4712

In [38]:
# 对类别0演示精确率, 召回率和F1分数的算法
y_test1 = np.where(y_test == 0, 1, 0)
# 在测试集中, 如果标签是0, 则改为1, 否则改为0
print(y_test1.sum())
# 得到的是测试集属于类别0的样本数(TP+FN)
y_predict1 = np.where(y_predict == 0, 1, 0)
print(y_predict1.sum())
# 得到预测集属于类别0的样本数(TP+FP)

199
168

In [39]:
t=(y_test1*y_predict1).sum()
print(t)
# 只有两个都为1, 才是TP

153

In [40]:
print('精确率:', t/(y_predict1.sum()))
print('召回率:', t/(y_test1.sum()))
print('F1分数:', 2*t/(y_predict1.sum()+y_test1.sum()))

精确率: 0.9107142857142857
召回率: 0.7688442211055276
F1分数: 0.8337874659400545

In [41]:
y_test1 = np.where(y_test == 0, 1, 0)
print(y_test1.sum()) 
y_predict1 = np.where(y_predict == 0, 1, 0)
print(y_predict1.sum())
# roc_auc_score的y_test只能是二分类,针对多分类如何计算AUC
print("AUC指标：", roc_auc_score(y_test1, y_predict1))

199
168
AUC指标： 0.8827602448315142

In [42]:
del news
del x_train
del x_test
del y_test
del y_predict
del tf

# 决策树

ID3(香农熵)计算信息增益, 会偏向特征值多的特征, 使特征值多的特征更可能放在根节点  
CD4.5 计算信息增益率, 减小对多值特征的偏向, 但是计算复杂   
CART使用基尼指数  
基尼值公式是1-sum(p_i^2), 即根据某项特征分类后, 信息的"纯度"(越小越纯)  
基尼系数就是基尼值乘以概率权重    
对每个特征尝试分裂, 如果分裂前后基尼指数下降最多(纯度提升最多), 则用该特征分裂

优点:  
容易解释和可视化  
不需要很多的数据预处理, 不需要归一化和标准化   
缺点:  
不能使用过于复杂的树, 容易过拟合   
很小的数据变化就会导致完全不同的树(弱分类器)

预测泰坦尼克号乘客的生还情况

In [43]:
titan = pd.read_csv("./data/titanic.txt")
print(titan.info())
titan

<class 'pandas.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   row.names  1313 non-null   int64
 1   pclass     1313 non-null   str
 2   survived   1313 non-null   int64
 3   name       1313 non-null   str
 4   age        633 non-null    float64
 5   embarked   821 non-null    str
 6   home.dest  754 non-null    str
 7   room       77 non-null     str
 8   ticket     69 non-null     str
 9   boat       347 non-null    str
 10  sex        1313 non-null   str
dtypes: float64(1), int64(2), str(8)
memory usage: 113.0 KB
None

,row.names,pclass,survived,name,age,embarked,home.dest,room,ticket,boat,sex
0,1,1st,1,"Allen, Miss Elisabeth Walton",29.0000,Southampton,"St Louis, MO",B-5,24160 L221,2,female
1,2,1st,0,"Allison, Miss Helen Loraine",2.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,NaN,female
2,3,1st,0,"Allison, Mr Hudson Joshua Creighton",30.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,(135),male
3,4,1st,0,"Allison, Mrs Hudson J.C. (Bessie Waldo Daniels)",25.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,NaN,female
4,5,1st,1,"Allison, Master Hudson Trevor",0.9167,Southampton,"Montreal, PQ / Chesterville, ON",C22,NaN,11,male
...,...,...,...,...,...,...,...,...,...,...,...
1308,1309,3rd,0,"Zakarian, Mr Artun",NaN,NaN,NaN,NaN,NaN,NaN,male
1309,1310,3rd,0,"Zakarian, Mr Maprieder",NaN,NaN,NaN,NaN,NaN,NaN,male
1310,1311,3rd,0,"Zenn, Mr Philip",NaN,NaN,NaN,NaN,NaN,NaN,male
1311,1312,3rd,0,"Zievens, Rene",NaN,NaN,NaN,NaN,NaN,NaN,female
1312,1313,3rd,0,"Zimmerman, Leo",NaN,NaN,NaN,NaN,NaN,NaN,male

In [44]:
x = titan.loc[:,['pclass', 'age', 'sex']]
# 设置船舱等级, 年龄, 性别为特征
y = titan.loc[:,'survived']
# 设置是否生还为标签
print(x.info())  # 用来判断是否有空值
x.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   pclass  1313 non-null   str
 1   age     633 non-null    float64
 2   sex     1313 non-null   str
dtypes: float64(1), str(2)
memory usage: 30.9 KB
None

       pclass         age   sex
count    1313  633.000000  1313
unique      3         NaN     2
top       3rd         NaN  male
freq      711         NaN   850
mean      NaN   31.194181   NaN
std       NaN   14.747525   NaN
min       NaN    0.166700   NaN
25%       NaN   21.000000   NaN
50%       NaN   30.000000   NaN
75%       NaN   41.000000   NaN
max       NaN   71.000000   NaN

In [45]:
mean=x['age'].mean()
x.loc[:,'age']=x.loc[:,'age'].fillna(mean)
# 用平均数填充空值年龄
x.describe(include='all')

       pclass          age   sex
count    1313  1313.000000  1313
unique      3          NaN     2
top       3rd          NaN  male
freq      711          NaN   850
mean      NaN    31.194181   NaN
std       NaN    10.235540   NaN
min       NaN     0.166700   NaN
25%       NaN    30.000000   NaN
50%       NaN    31.194181   NaN
75%       NaN    31.194181   NaN
max       NaN    71.000000   NaN

In [55]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=4)
print(x_train.head())

    pclass        age     sex
598    2nd  30.000000    male
246    1st  62.000000    male
905    3rd  31.194181  female
300    1st  31.194181  female
509    2nd  64.000000    male

In [47]:
# 以下说明性别是重要的特征
z=x_train.copy() 
# z是为了把特征和目标存储到一起
z['survived'] = y_train #把目标值存储到z中
z

     pclass        age     sex  survived
598     2nd  30.000000    male         0
246     1st  62.000000    male         0
905     3rd  31.194181  female         0
300     1st  31.194181  female         0
509     2nd  64.000000    male         0
...     ...        ...     ...       ...
360     2nd  31.194181    male         0
709     3rd  28.000000    male         0
439     2nd  34.000000    male         0
174     1st  46.000000    male         0
1146    3rd  31.194181    male         0

[984 rows x 4 columns]

In [48]:
z[z['sex'] == 'female']['survived'].value_counts()  
# sex列为female的情况下, 按照survived分组, value_counts()统计个数

survived
1    230
0    111
Name: count, dtype: int64

In [49]:
z[z['sex'] == 'male']['survived'].value_counts()

survived
0    539
1    104
Name: count, dtype: int64

In [50]:
z['survived'].value_counts()  # 一共有650个死亡, 334个存活

survived
0    650
1    334
Name: count, dtype: int64

In [56]:
from sklearn.feature_extraction import DictVectorizer

dit = DictVectorizer(sparse=False)
print(x_train.to_dict(orient="records")[0:5])
x_train = dit.fit_transform(x_train.to_dict(orient="records"))
# to_dict转换x_train为字典列表，records代表一行一个字典
# 字典矢量器, 将字典列表转化为one-hot编码
print(type(x_train))
print(dit.get_feature_names_out())
print('-' * 50)
x_test = dit.transform(x_test.to_dict(orient="records"))
# 对测试集进行处理
print(x_test)

[{'pclass': '2nd', 'age': 30.0, 'sex': 'male'}, {'pclass': '1st', 'age': 62.0, 'sex': 'male'}, {'pclass': '3rd', 'age': 31.19418104265403, 'sex': 'female'}, {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'}, {'pclass': '2nd', 'age': 64.0, 'sex': 'male'}]
<class 'numpy.ndarray'>
['age' 'pclass=1st' 'pclass=2nd' 'pclass=3rd' 'sex=female' 'sex=male']
--------------------------------------------------
[[27.          0.          1.          0.          1.          0.        ]
 [21.          0.          1.          0.          0.          1.        ]
 [39.          1.          0.          0.          0.          1.        ]
 ...
 [28.          0.          1.          0.          1.          0.        ]
 [31.19418104  0.          0.          1.          0.          1.        ]
 [31.19418104  0.          0.          1.          0.          1.        ]]

In [52]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
# 使用决策树进行分类
dec = DecisionTreeClassifier()
dec.fit(x_train, y_train)
# 训练, 构建决策树
print("预测的准确率：", dec.score(x_test, y_test))
# 预测准确率
export_graphviz(dec, out_file="tree.dot",
                feature_names=['age', 'pclass=1st', 'pclass=2nd',
                               'pclass=3rd', 'female', 'male'])
# 导出决策树的结构

预测的准确率： 0.8085106382978723

对决策树进行参数调优

In [58]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)
dict1 = DictVectorizer(sparse=False)
# 注意不需要归一化, 因为算的是概率

x_train = dict1.fit_transform(x_train.to_dict(orient="records"))
x_test = dict1.transform(x_test.to_dict(orient="records"))

# print(x_train)

dec = DecisionTreeClassifier(max_depth=7,min_impurity_decrease=0.01,min_samples_split=20)
# 调整决策树超参数, max_depth最大深度, 越大越容易过拟合
# min_impurity_decrease纯度改善, 只有纯度改善大于0.01才会分裂, 越小越容易过拟合
# min_samples_split最小样本数, 一个节点至少有20个样本才会尝试分裂, 越小越容易过拟合
# 调整这三个参数, 实际上是"预剪枝"
dec.fit(x_train, y_train)
print("预测的准确率：", dec.score(x_test, y_test))

export_graphviz(dec, out_file="tree1.dot",
                feature_names=['age', 'pclass=1st', 'pclass=2nd',
                'pclass=3rd', 'female', 'male'])

预测的准确率： 0.851063829787234

# 随机森林

适用于特征复杂, 样本多的情况(泰坦尼克太小了)

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)
dict2 = DictVectorizer(sparse=False)

x_train = dict2.fit_transform(x_train.to_dict(orient="records"))
x_test = dict2.transform(x_test.to_dict(orient="records"))

In [62]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=-1)
# n_jobs=-1, 使用所有CPU
param = {
    "n_estimators": [100, 300, 500],
    # 树的数量
    "max_depth": [3, 5, 7, 10],
    # 最大深度
    "min_samples_split": [5, 10, 20],
    # 分裂的最小样本数
    "min_samples_leaf": [1, 2, 5],
    # 叶子节点的最小样本数
    "max_features": ["sqrt", "log2", None]
    # 随机选取特征的个数, 总特征数的平方, 总特征数的对数, 取全部特征
    # 但在特征只有三个的情况下, 一般取全部特征, 实际上退化成普通树
    # 还可以使用的参数:
    # bootstrap: 是否有放回抽样(默认为True), 否则使用全部数据
    # 注意是有放回, 大约只会选中63.2%的数据
    # max_samples: 每棵树使用多少样本(配合bootstrap=True)
}
# 网格搜索(选参数)和交叉验证(算结果)
gc = GridSearchCV(rf, param_grid=param, cv=3)

gc.fit(x_train, y_train)

print("最好的准确率：", gc.score(x_test, y_test))

print("选择的参数：", gc.best_params_)

最好的准确率： 0.851063829787234
选择的参数： {'max_depth': 3, 'max_features': None, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 100}

In [63]:
gc.cv_results_

{'mean_fit_time': array([0.1131072 , 0.32485938, 0.51980583, 0.11182817, 0.32031059,
        0.51212668, 0.11455321, 0.31422377, 0.50918674, 0.114115  ,
        0.3126328 , 0.51390282, 0.11343479, 0.31105399, 0.53696036,
        0.11457419, 0.3671728 , 0.56358449, 0.1186254 , 0.33736436,
        0.56497741, 0.14163717, 0.38351258, 0.51838533, 0.16551725,
        0.31348006, 0.52622755, 0.11431805, 0.31881523, 0.63995814,
        0.11496981, 0.31416917, 0.52947593, 0.15765842, 0.39465451,
        0.5433507 , 0.1433545 , 0.32660882, 0.63836527, 0.11490766,
        0.31120952, 0.54846891, 0.11284208, 0.38590034, 0.51559218,
        0.10738238, 0.31142791, 0.5207684 , 0.11182563, 0.3245515 ,
        0.60753981, 0.1115063 , 0.30812716, 0.51307662, 0.11249224,
        0.3369112 , 0.58232443, 0.11218659, 0.34607553, 0.57096513,
        0.11197074, 0.30670238, 0.54967833, 0.11750452, 0.35403991,
        0.61764844, 0.11825848, 0.30969779, 0.51586429, 0.1116852 ,
        0.3181928 , 0.51407758, 0.11237256, 0.31138388, 0.51396497,
        0.11668682, 0.31540235, 0.54797514, 0.1146431 , 0.3285385 ,
        0.52205761, 0.11425598, 0.33795436, 0.53882138, 0.12039248,
        0.32507364, 0.51989126, 0.12472216, 0.31639258, 0.54336603,
        0.1111211 , 0.31942336, 0.5386041 , 0.11142834, 0.31951873,
        0.53516698, 0.12074518, 0.38433814, 0.57526906, 0.11577956,
        0.33059478, 0.51646272, 0.11373019, 0.3189501 , 0.51161718,
        0.10891859, 0.32030447, 0.51065882, 0.1187319 , 0.32493265,
        0.51745566, 0.14528712, 0.31400442, 0.52346436, 0.10923235,
        0.39592147, 0.54181671, 0.1141781 , 0.31941168, 0.56399767,
        0.13326573, 0.31336864, 0.58421286, 0.11143549, 0.31391827,
        0.53286974, 0.14405608, 0.37257894, 0.58403619, 0.11094213,
        0.36899598, 0.61649656, 0.11275029, 0.38138008, 0.59280578,
        0.11417754, 0.36058402, 0.52100945, 0.15271235, 0.31076884,
        0.62655894, 0.11301883, 0.3930889 , 0.58218161, 0.12189698,
        0.3681337 , 0.53443154, 0.11331622, 0.33924063, 0.52455719,
        0.11674968, 0.32240645, 0.57813819, 0.11995562, 0.41586336,
        0.61030094, 0.11246419, 0.36717836, 0.54156979, 0.11435239,
        0.32202522, 0.55369592, 0.11521912, 0.36683583, 0.52470167,
        0.11652017, 0.36376635, 0.57713   , 0.11320964, 0.34496951,
        0.59225957, 0.11829726, 0.31214968, 0.51314116, 0.11083213,
        0.34477512, 0.59645311, 0.13989472, 0.3618904 , 0.5152723 ,
        0.11079884, 0.46435078, 0.54108334, 0.10939693, 0.30819472,
        0.52357117, 0.10751828, 0.30987032, 0.50909225, 0.11230548,
        0.31691559, 0.5128177 , 0.14236871, 0.30997388, 0.52897795,
        0.11342255, 0.31246996, 0.51922003, 0.11464898, 0.32079196,
        0.57957737, 0.11032677, 0.39167182, 0.52996826, 0.11322411,
        0.30959868, 0.53995124, 0.11849952, 0.31928452, 0.52179321,
        0.11383025, 0.31693888, 0.53167256, 0.11698882, 0.32038363,
        0.52183811, 0.12335841, 0.32229106, 0.57236147, 0.11278598,
        0.30896314, 0.50953062, 0.11086575, 0.31021833, 0.53530081,
        0.11270793, 0.31380089, 0.51898623, 0.11223912, 0.31375035,
        0.51409801, 0.11240307, 0.31006034, 0.51058245, 0.10942451,
        0.31297159, 0.51568182, 0.11433172, 0.31261659, 0.51473753,
        0.11532227, 0.31132364, 0.5195694 , 0.11117792, 0.32213203,
        0.51593558, 0.11091598, 0.31769514, 0.51274745, 0.11299102,
        0.31573621, 0.51590967, 0.11493715, 0.32375558, 0.51685111,
        0.11132058, 0.32005246, 0.51275317, 0.11424716, 0.31638869,
        0.51312073, 0.11186592, 0.31197206, 0.51097751, 0.11631656,
        0.36296209, 0.53154357, 0.11489717, 0.31483754, 0.52195962,
        0.11702991, 0.32060687, 0.52859028, 0.11401073, 0.32579517,
        0.52200786, 0.11361766, 0.32238038, 0.5271008 , 0.11505421,
        0.32489411, 0.53703785, 0.10879024, 0.32562327, 0.52844779,
        0.11625838, 0.33555245, 0.53399348, 0.11439967, 0.31874808,
        0.52800759, 0.11582653, 0.34642394, 0.52287936, 0.12199871,
        0.32692202, 0.520751  , 0.12425574, 0.33186046, 0.52478782,
        0.11222847, 0.32210493, 0.51567705, 0.112312  , 0.31273882,
        0.51669431, 0.11379743, 0.31032658, 0.50759315, 0.10921009,
        0.31188281, 0.51466807, 0.11417953, 0.31209834, 0.51260217,
        0.10990945, 0.31152868, 0.59436242, 0.1282692 , 0.33647712,
        0.51779238, 0.13144843, 0.32798998, 0.59774494]),
 'std_fit_time': array([3.15054493e-04, 1.12389111e-02, 7.45544366e-03, 9.78029014e-04,
        4.78656635e-04, 1.02361451e-02, 6.42554266e-03, 1.22263880e-03,
        3.60684971e-03, 8.81155482e-04, 7.04323777e-03, 5.57716403e-03,
        1.60604366e-04, 5.41283145e-03, 1.75421816e-02, 3.72074096e-03,
        4.70297666e-02, 3.98134432e-02, 7.55251838e-03, 1.93938408e-02,
        3.22999029e-02, 1.92049770e-02, 4.13377668e-02, 4.16001853e-03,
        2.91634172e-02, 5.56922647e-03, 6.38629328e-03, 2.75583707e-03,
        1.95501299e-03, 9.06277579e-02, 2.42021693e-03, 4.69387475e-03,
        2.40945765e-02, 4.97411351e-02, 5.59825046e-02, 3.59183939e-02,
        2.07872696e-02, 4.98203367e-03, 4.43653095e-02, 2.25073915e-03,
        2.69746300e-03, 4.52510892e-02, 1.70175447e-03, 5.10150583e-02,
        1.04865318e-02, 9.56328242e-04, 2.73267511e-03, 7.47387709e-03,
        3.01496394e-03, 6.87101372e-03, 6.54635134e-02, 2.95498174e-03,
        3.52934704e-03, 7.90940436e-03, 2.45092198e-03, 3.32352475e-02,
        1.02483254e-01, 1.77753518e-03, 4.71183199e-02, 8.65821694e-02,
        3.07100785e-03, 2.70453909e-03, 3.60552188e-02, 8.50477634e-04,
        4.02846926e-02, 6.79988071e-02, 8.01510692e-03, 4.50329764e-03,
        7.09673475e-03, 4.15849088e-04, 1.36379327e-02, 2.36407977e-03,
        2.56551583e-03, 4.04402985e-03, 2.45222516e-03, 7.14466216e-04,
        6.02174035e-03, 1.40981755e-02, 1.65474267e-03, 8.55569958e-03,
        3.12376999e-03, 2.79504281e-03, 1.17244227e-02, 6.02850372e-03,
        4.02533936e-03, 7.39204504e-03, 1.06988063e-04, 6.58710036e-03,
        8.53460398e-04, 3.29083462e-02, 1.89327268e-03, 1.65437636e-03,
        8.38905604e-03, 1.17011255e-03, 2.74509207e-03, 1.16225962e-02,
        4.93320494e-03, 2.61380246e-02, 7.31492876e-02, 3.55088080e-03,
        2.07844276e-02, 1.53681910e-02, 1.81680724e-03, 9.54375121e-03,
        3.35607840e-03, 2.29555095e-03, 8.26438500e-03, 2.54394672e-03,
        2.95789025e-03, 4.98228938e-03, 1.15089555e-02, 4.25690741e-02,
        3.63937420e-03, 9.67578620e-03, 8.24777279e-04, 6.08178678e-02,
        2.29328926e-02, 2.36616480e-03, 4.43282232e-03, 5.03933930e-02,
        1.59819615e-02, 3.39751206e-03, 5.97596130e-02, 1.89680649e-03,
        6.56058243e-03, 1.20993532e-02, 2.03118954e-02, 8.63369420e-02,
        7.99080263e-02, 1.05813176e-03, 6.59486075e-02, 6.78140175e-02,
        4.52188764e-03, 2.12691729e-02, 4.33012668e-02, 2.30954844e-03,
        4.41480482e-02, 4.35126227e-03, 3.67760123e-02, 3.64184295e-03,
        4.08814034e-02, 7.83944221e-03, 7.68726943e-02, 4.36312050e-02,
        9.62598986e-03, 2.95492458e-02, 2.06878612e-02, 2.06638040e-03,
        3.42389911e-02, 2.42964299e-03, 1.17453072e-03, 9.80235902e-03,
        6.45801767e-02, 7.32033212e-04, 8.03657696e-02, 2.04749327e-02,
        1.35677096e-03, 5.42648471e-02, 4.70559779e-02, 6.97491673e-03,
        7.26656702e-03, 4.54601986e-02, 3.46620477e-03, 2.27099559e-02,
        5.00240610e-03, 2.81843601e-03, 6.87560038e-02, 4.52087953e-02,
        3.95521501e-03, 4.75804356e-02, 3.93522492e-02, 3.14602874e-03,
        1.38248067e-03, 5.55787757e-03, 2.43283917e-03, 3.87358296e-02,
        1.14395235e-01, 4.29805305e-02, 1.06080596e-02, 3.98419461e-03,
        2.60106287e-03, 1.71656075e-02, 1.84786071e-02, 4.56766519e-03,
        9.84837599e-04, 1.09101679e-02, 1.72474813e-03, 1.94860200e-03,
        1.06176696e-03, 2.98863401e-03, 1.23364080e-03, 7.41005359e-03,
        3.13542608e-02, 6.54571000e-04, 1.62040436e-02, 3.21744402e-03,
        4.40594772e-03, 9.67358984e-03, 7.31258928e-04, 8.34280245e-03,
        7.90564256e-02, 3.74700502e-03, 8.53586934e-02, 1.74628943e-02,
        2.37518862e-03, 4.76457839e-03, 4.14878820e-02, 1.00719366e-03,
        2.01044412e-03, 3.43559507e-03, 2.89799595e-03, 7.20391425e-03,
        2.63657181e-02, 3.90752734e-03, 1.33819540e-02, 3.04793042e-03,
        1.51791150e-02, 1.32585475e-02, 4.70234667e-02, 3.75574794e-03,
        3.91336500e-03, 2.99708428e-03, 3.41495409e-03, 1.29497248e-03,
        1.85934913e-02, 6.35289627e-04, 6.32456604e-03, 8.14827614e-03,
        1.07352465e-03, 4.85926012e-03, 9.01135026e-03, 2.54582127e-03,
        1.48130945e-03, 7.49214392e-04, 3.75526593e-03, 6.39236132e-03,
        3.01187599e-03, 1.15338306e-03, 4.59546925e-03, 1.29067223e-02,
        1.98595779e-03, 4.64868943e-03, 7.62132650e-04, 3.53147515e-03,
        8.46429294e-03, 7.63724250e-04, 1.58478925e-03, 2.17448913e-03,
        2.90683734e-03, 2.55235112e-03, 2.84276079e-03, 4.16846682e-03,
        2.77381886e-03, 9.80521333e-03, 1.86830754e-03, 3.06221180e-03,
        2.03466880e-04, 3.50057642e-03, 2.24785521e-03, 3.12577318e-03,
        4.07133674e-03, 2.37939761e-03, 1.55702076e-03, 2.63530690e-03,
        1.73480588e-03, 1.30890508e-02, 2.22097412e-02, 5.99537049e-04,
        1.95433310e-03, 5.15899306e-03, 8.45434590e-04, 6.66989185e-03,
        5.68184354e-03, 1.17435930e-03, 1.14123390e-02, 5.21215131e-03,
        1.28498919e-03, 3.45136352e-03, 1.80470672e-03, 2.66337505e-03,
        5.09452506e-03, 3.53379185e-03, 8.31821075e-04, 1.50245723e-02,
        1.35923207e-02, 5.95731496e-03, 2.38287420e-03, 1.08594592e-02,
        4.53583352e-04, 5.75282990e-03, 5.12382672e-03, 5.79031454e-03,
        2.39733857e-02, 6.38346162e-03, 2.73671064e-03, 3.63143409e-03,
        6.80473823e-03, 4.18054001e-03, 1.92316929e-02, 6.14723759e-03,
        5.07540639e-03, 1.65246410e-02, 2.26139452e-03, 2.02409803e-03,
        3.33917814e-03, 3.86391354e-03, 4.38025510e-03, 2.27127665e-03,
        2.31920188e-03, 3.98263754e-03, 4.07826453e-03, 9.41594656e-04,
        2.07238059e-03, 2.00061512e-03, 8.18561705e-03, 1.57922216e-03,
        2.26176428e-03, 2.77087346e-02, 9.27434855e-03, 1.37457558e-02,
        1.07561102e-02, 2.23144472e-02, 4.32374985e-03, 5.50195142e-02]),
 'mean_score_time': array([0.0239021 , 0.03849244, 0.06692251, 0.02692898, 0.04626083,
        0.07110127, 0.02740908, 0.04576373, 0.08099047, 0.02601504,
        0.04182784, 0.06937083, 0.01891104, 0.04801488, 0.07040977,
        0.01879764, 0.06701136, 0.06447331, 0.03235507, 0.05954448,
        0.09683728, 0.05443271, 0.04533386, 0.06993691, 0.02567951,
        0.04266024, 0.06751418, 0.02230501, 0.05325659, 0.06646713,
        0.02632531, 0.04115208, 0.06176376, 0.03587437, 0.04142761,
        0.15023756, 0.02795005, 0.03921731, 0.06270504, 0.0262897 ,
        0.05108523, 0.09391038, 0.02632499, 0.06003014, 0.06571078,
        0.02272598, 0.04092518, 0.06926123, 0.04744291, 0.04776549,
        0.07793784, 0.02601512, 0.04159697, 0.07026505, 0.02322245,
        0.04145614, 0.06339892, 0.02613529, 0.03728676, 0.06288155,
        0.01900665, 0.05439353, 0.06290062, 0.02633603, 0.04087138,
        0.06807597, 0.02653352, 0.04256749, 0.06388458, 0.01926835,
        0.04207627, 0.06383729, 0.02303974, 0.0378929 , 0.06648326,
        0.02637355, 0.03768913, 0.06891799, 0.02614236, 0.05007577,
        0.06576324, 0.0264523 , 0.0522422 , 0.06838838, 0.0263323 ,
        0.04833841, 0.06892363, 0.02663064, 0.04758128, 0.07617299,
        0.02610358, 0.04795861, 0.07233572, 0.02648147, 0.04745436,
        0.08280929, 0.02685849, 0.06251812, 0.07191332, 0.02652756,
        0.04774316, 0.0683097 , 0.02588312, 0.04703856, 0.06844958,
        0.02588948, 0.04771455, 0.07188153, 0.02693057, 0.04770581,
        0.07233214, 0.02617844, 0.07551257, 0.06826051, 0.02624695,
        0.05826545, 0.06861583, 0.02563357, 0.04766456, 0.08546154,
        0.02750866, 0.0475378 , 0.06844497, 0.02599176, 0.04958367,
        0.10110021, 0.02791079, 0.04700828, 0.09260599, 0.02616477,
        0.04763508, 0.07920233, 0.02763756, 0.05324157, 0.07539598,
        0.02729543, 0.05474051, 0.07253838, 0.03350925, 0.0471162 ,
        0.07279134, 0.0267961 , 0.0485417 , 0.08416295, 0.04575523,
        0.05155945, 0.07933855, 0.02648052, 0.05400046, 0.07832686,
        0.02675239, 0.07796033, 0.07208665, 0.05252028, 0.0482618 ,
        0.07208323, 0.02620927, 0.0539283 , 0.08096059, 0.0265433 ,
        0.06196086, 0.07260712, 0.0264051 , 0.05622832, 0.07175295,
        0.02685229, 0.04756172, 0.09739025, 0.02617963, 0.05118322,
        0.08017023, 0.02630544, 0.04701138, 0.06825105, 0.02597594,
        0.0469981 , 0.0698607 , 0.02652351, 0.06832091, 0.10309227,
        0.02683632, 0.05651951, 0.08660277, 0.02587056, 0.04739332,
        0.07262063, 0.02654521, 0.04724979, 0.07127182, 0.02695608,
        0.05129615, 0.07169684, 0.02661236, 0.05052543, 0.06833196,
        0.02606042, 0.04786817, 0.068494  , 0.02684132, 0.04872767,
        0.07229543, 0.02608625, 0.08188685, 0.07154846, 0.0258402 ,
        0.0786376 , 0.07552354, 0.02684601, 0.04778322, 0.07931185,
        0.02679976, 0.05102833, 0.06883725, 0.02726293, 0.04736924,
        0.07186095, 0.03052147, 0.04717135, 0.08262952, 0.04083991,
        0.04727213, 0.06819073, 0.0259157 , 0.04705445, 0.0768048 ,
        0.02618686, 0.04733674, 0.07190681, 0.02602895, 0.05120508,
        0.06813471, 0.02634788, 0.04731321, 0.06848439, 0.02617168,
        0.04703554, 0.06779989, 0.02628501, 0.04789654, 0.07234168,
        0.02628295, 0.04735382, 0.07262762, 0.0258317 , 0.04685823,
        0.09165112, 0.0266126 , 0.04805764, 0.06834356, 0.02584902,
        0.04718232, 0.07219744, 0.02636838, 0.04745722, 0.07164065,
        0.02632372, 0.04713861, 0.07147439, 0.0263652 , 0.04790457,
        0.06859104, 0.02638443, 0.04777161, 0.06829508, 0.02651501,
        0.04840938, 0.06876024, 0.02613839, 0.05530183, 0.06811531,
        0.02700424, 0.04753224, 0.06878002, 0.04381402, 0.04549948,
        0.07118026, 0.02635479, 0.04747542, 0.06988462, 0.0267597 ,
        0.04841868, 0.07263629, 0.02657239, 0.04955808, 0.07226745,
        0.02671051, 0.05315081, 0.08017135, 0.02602919, 0.04738704,
        0.07237911, 0.02695855, 0.04779283, 0.07224154, 0.02717304,
        0.0476466 , 0.06807335, 0.02657104, 0.04763047, 0.07868989,
        0.02288683, 0.04715276, 0.06852841, 0.02643585, 0.04752922,
        0.07166902, 0.02615833, 0.04716428, 0.06839585, 0.02627842,
        0.0471758 , 0.0676101 , 0.02588844, 0.04740047, 0.06886443,
        0.02586635, 0.04780714, 0.08573699, 0.02714388, 0.05151232,
        0.06949385, 0.02604405, 0.04833937, 0.08083328]),
 'std_score_time': array([4.04678600e-03, 1.10938863e-03, 3.91504827e-03, 2.13328131e-04,
        3.44502251e-03, 7.46272053e-03, 9.05051937e-04, 5.68994305e-03,
        2.96287540e-02, 4.94307937e-04, 5.78006933e-03, 8.88825237e-04,
        5.44775840e-03, 5.55617026e-04, 8.72391046e-03, 4.88060153e-03,
        3.38887818e-02, 3.06454781e-03, 6.85665448e-03, 1.55640696e-02,
        3.94743719e-02, 2.81679996e-02, 4.48488025e-03, 5.47366216e-04,
        7.49513648e-03, 4.37547055e-03, 3.65942844e-03, 5.14076670e-03,
        3.87406483e-03, 5.30907663e-03, 4.13354120e-04, 4.72737365e-03,
        1.59968435e-03, 9.62579366e-03, 5.18808648e-03, 5.84504914e-02,
        1.29099098e-03, 3.43219332e-04, 2.19909228e-03, 4.44066407e-04,
        1.08878174e-02, 4.75803101e-02, 8.09460629e-05, 1.60734349e-02,
        4.61901872e-03, 4.94075562e-03, 4.81395689e-03, 2.01280091e-03,
        3.72399377e-02, 8.32818064e-04, 2.41096918e-02, 2.94362816e-04,
        4.05415539e-03, 2.74515447e-03, 4.85634960e-03, 5.74862236e-03,
        4.53135630e-03, 1.74378196e-04, 7.38918221e-04, 4.74355283e-03,
        4.92179836e-03, 2.41422869e-02, 5.02962274e-03, 1.79815911e-04,
        5.56192173e-03, 2.55703589e-03, 7.06009798e-05, 3.43551318e-03,
        4.50280193e-03, 4.72666701e-03, 6.27052726e-03, 4.64720088e-03,
        4.65468801e-03, 8.96711205e-04, 5.07731032e-03, 3.79632177e-04,
        1.02261154e-03, 4.60478970e-03, 5.24381742e-04, 1.33653791e-03,
        5.06309423e-03, 3.49695827e-04, 5.08879772e-03, 9.61133482e-04,
        6.85956738e-04, 4.99791805e-04, 1.08303198e-03, 2.33737855e-04,
        4.86889280e-04, 5.54336021e-03, 2.52280231e-04, 4.50288987e-04,
        5.34847015e-03, 6.32778729e-04, 1.60627724e-04, 5.13633626e-03,
        4.78860747e-05, 2.15260245e-02, 5.35703211e-03, 4.43123633e-04,
        8.44581371e-04, 1.40913560e-04, 4.92419675e-04, 3.29437771e-04,
        5.85634764e-04, 4.50908906e-04, 7.93528246e-04, 5.08068037e-03,
        8.03661347e-04, 1.07610629e-03, 5.56481617e-03, 3.42660190e-04,
        3.93045235e-02, 5.61158071e-04, 6.44002590e-04, 1.51228857e-02,
        2.03389945e-04, 1.42896224e-04, 4.49901579e-04, 1.62587159e-02,
        4.42265557e-04, 4.21895043e-04, 3.91609659e-04, 4.96599987e-04,
        3.89839365e-03, 4.64612209e-02, 2.05950811e-03, 6.46750669e-04,
        3.43649277e-02, 2.36544956e-04, 1.79326383e-04, 8.53184128e-03,
        2.20540427e-03, 7.99148438e-03, 4.55974172e-03, 2.67875579e-04,
        9.51052338e-03, 5.82897938e-03, 5.40857133e-03, 6.14563814e-04,
        5.12253079e-03, 1.36303629e-03, 6.25663695e-04, 1.13342266e-02,
        2.78324824e-02, 5.73793639e-03, 9.78291035e-03, 4.52872575e-04,
        8.74180296e-03, 4.77164527e-04, 1.88616104e-04, 3.83047511e-02,
        5.32085395e-03, 3.67065448e-02, 1.82516616e-03, 3.07251691e-03,
        4.71314409e-04, 8.83921670e-03, 1.67035035e-02, 9.03392721e-04,
        2.14836280e-02, 5.84001716e-03, 3.97002946e-04, 1.30887248e-02,
        5.12110268e-03, 7.53805206e-04, 1.87080800e-04, 3.41050087e-02,
        1.71130775e-04, 5.34929689e-03, 1.60440310e-02, 2.63964794e-04,
        2.44870390e-04, 2.78916746e-04, 8.65109625e-04, 4.41300933e-04,
        2.38087855e-03, 6.63113274e-05, 3.03212450e-02, 4.91245162e-02,
        8.13630880e-04, 1.13424226e-02, 1.85452690e-02, 2.43608804e-04,
        2.45886742e-04, 5.14483678e-03, 4.08055671e-04, 1.09744423e-03,
        5.58422369e-03, 1.07269768e-03, 5.22462825e-03, 5.13753274e-03,
        6.57621467e-05, 5.42700491e-03, 3.35655596e-04, 1.99764736e-04,
        1.41601655e-03, 7.20606955e-04, 1.94599841e-04, 1.29692141e-03,
        4.83104555e-03, 3.01656783e-04, 4.55669507e-02, 5.72262209e-03,
        5.38882613e-04, 4.36246907e-02, 5.14712099e-03, 7.01167310e-04,
        4.15048575e-04, 3.45115210e-04, 3.52783900e-04, 5.05165384e-03,
        7.70793177e-04, 5.63794291e-04, 4.33732916e-04, 5.00795799e-03,
        5.33283367e-03, 4.24045434e-04, 2.04493984e-02, 2.12379881e-02,
        2.88983338e-04, 1.04447355e-04, 2.41819941e-04, 3.18255038e-04,
        5.67291179e-03, 1.23169498e-04, 4.44439233e-04, 4.95086620e-03,
        2.12680628e-04, 5.15497835e-03, 3.19548638e-04, 2.27510880e-04,
        2.55380541e-04, 2.14411030e-04, 4.22242243e-04, 2.64634265e-04,
        8.58156631e-04, 7.10084669e-04, 7.07440203e-04, 5.52460054e-03,
        2.27532643e-04, 4.13516634e-04, 5.38433096e-03, 2.74727733e-04,
        8.41529402e-05, 2.61478405e-02, 5.44175886e-04, 9.05999663e-04,
        5.49775196e-04, 4.41867499e-04, 3.44351545e-04, 5.62524978e-03,
        4.36595697e-04, 1.13217617e-04, 4.55143775e-03, 3.56805828e-04,
        1.96321193e-04, 5.24712914e-03, 5.31845262e-04, 1.00684393e-03,
        1.86740184e-04, 3.00619158e-04, 2.31763898e-05, 3.79309565e-05,
        4.86325904e-04, 1.88847415e-04, 5.23969850e-04, 3.56251736e-04,
        1.10034911e-02, 5.59431345e-04, 1.93297437e-04, 5.83860582e-04,
        2.19011081e-04, 2.43898514e-02, 3.67096894e-03, 5.09177300e-03,
        7.37717504e-04, 7.44803699e-04, 9.83068590e-04, 5.18074460e-04,
        1.32908397e-03, 5.51253069e-03, 7.25521077e-04, 3.16836505e-03,
        5.36397711e-03, 6.73198856e-04, 6.81832143e-03, 1.36648436e-03,
        6.59521824e-04, 4.70854434e-04, 5.49603274e-03, 7.72854736e-04,